name: CI/CD Workshop
on: [ push ]

jobs:
  build_golang:
    runs-on: ubuntu-latest
    steps:
    - name: setup golang
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.17.0'
    - run: go version

    - name: checkout source
      uses: actions/checkout@v3

    - name: setup railway cli
      run: yarn global add @railway/cli

    - name: list your repo
      run: ls -l