name: CI/CD Submission
on: [ push ]

jobs:
  build_golang:
    runs-on: ubuntu-latest
    steps:
    - name: setup golang
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.17.0'
    - run: go version

    - name: setup node js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: checkout source
      uses: actions/checkout@v3

    - name: setup railway cli
      run: yarn global add @railway/cli
    
    - name: deploy to railway
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}